FROM python:3.7.0-alpine3.8
WORKDIR /build
RUN apk add git
#clone my fork until 
RUN git clone https://github.com/schafezp/tgintegration.git
WORKDIR /build/tgintegration
RUN git checkout support_pyrogram_0.8.0
RUN python setup.py install


FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD src/tests.py /code/tests.py

CMD ["python3", "tests.py"]