FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD integration_requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
ADD src/tests.py /code/tests.py

CMD ["python3", "tests.py"]